<?php

namespace ContainerFm4eNlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Apps\\RestApi\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'Apps\\RestApi\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'Apps\\RestApi\\Modules\\Account\\Controllers\\BaseController::create' => ['privates', '.service_locator.pYS7Epo', 'get_ServiceLocator_PYS7EpoService', true],
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController::confirm' => ['privates', '.service_locator.Z5iDYiJ', 'get_ServiceLocator_Z5iDYiJService', true],
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController::create' => ['privates', '.service_locator.NHvVFpR', 'get_ServiceLocator_NHvVFpRService', true],
            'Apps\\RestApi\\Modules\\Sensor\\Controllers\\BaseController::create' => ['privates', '.service_locator.Ur5WswC', 'get_ServiceLocator_Ur5WswCService', true],
            'Apps\\RestApi\\Modules\\Session\\Controllers\\BaseController::refresh' => ['privates', '.service_locator.Cxblggg', 'get_ServiceLocator_CxblgggService', true],
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController::authenticate' => ['privates', '.service_locator.edq8ecD', 'get_ServiceLocator_Edq8ecDService', true],
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController::authorize' => ['privates', '.service_locator.oJvfy0Z', 'get_ServiceLocator_OJvfy0ZService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'Apps\\RestApi\\Modules\\Account\\Controllers\\BaseController:create' => ['privates', '.service_locator.pYS7Epo', 'get_ServiceLocator_PYS7EpoService', true],
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController:confirm' => ['privates', '.service_locator.Z5iDYiJ', 'get_ServiceLocator_Z5iDYiJService', true],
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController:create' => ['privates', '.service_locator.NHvVFpR', 'get_ServiceLocator_NHvVFpRService', true],
            'Apps\\RestApi\\Modules\\Sensor\\Controllers\\BaseController:create' => ['privates', '.service_locator.Ur5WswC', 'get_ServiceLocator_Ur5WswCService', true],
            'Apps\\RestApi\\Modules\\Session\\Controllers\\BaseController:refresh' => ['privates', '.service_locator.Cxblggg', 'get_ServiceLocator_CxblgggService', true],
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController:authenticate' => ['privates', '.service_locator.edq8ecD', 'get_ServiceLocator_Edq8ecDService', true],
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController:authorize' => ['privates', '.service_locator.oJvfy0Z', 'get_ServiceLocator_OJvfy0ZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'Apps\\RestApi\\Kernel::loadRoutes' => '?',
            'Apps\\RestApi\\Kernel::registerContainerConfiguration' => '?',
            'Apps\\RestApi\\Modules\\Account\\Controllers\\BaseController::create' => '?',
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController::confirm' => '?',
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController::create' => '?',
            'Apps\\RestApi\\Modules\\Sensor\\Controllers\\BaseController::create' => '?',
            'Apps\\RestApi\\Modules\\Session\\Controllers\\BaseController::refresh' => '?',
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController::authenticate' => '?',
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController::authorize' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'Apps\\RestApi\\Modules\\Account\\Controllers\\BaseController:create' => '?',
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController:confirm' => '?',
            'Apps\\RestApi\\Modules\\ConfirmationCode\\Controllers\\BaseController:create' => '?',
            'Apps\\RestApi\\Modules\\Sensor\\Controllers\\BaseController:create' => '?',
            'Apps\\RestApi\\Modules\\Session\\Controllers\\BaseController:refresh' => '?',
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController:authenticate' => '?',
            'Apps\\RestApi\\Modules\\User\\Controllers\\BaseController:authorize' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
