<?php

namespace ContainerFm4eNlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreating2Service extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private 'Apps\RestApi\Modules\Sensor\Services\Creating' shared autowired service.
     *
     * @return \Apps\RestApi\Modules\Sensor\Services\Creating
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/Modules/Sensor/Services/Creating.php';
        include_once \dirname(__DIR__, 6).'/Core/Sensor/UseCases/Creating.php';
        include_once \dirname(__DIR__, 6).'/Core/Sensor/Ports/Changing.php';
        include_once \dirname(__DIR__, 6).'/MySQLAdapters/Sensor/Creating.php';

        return $container->privates['Apps\\RestApi\\Modules\\Sensor\\Services\\Creating'] = new \Apps\RestApi\Modules\Sensor\Services\Creating(new \Core\Sensor\UseCases\Creating(new \MySQLAdapters\Sensor\Creating(), ($container->privates['Core\\User\\UseCases\\Authorization'] ?? $container->load('getAuthorization2Service'))));
    }
}
