<?php

namespace ContainerFm4eNlB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatingService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private 'Apps\RestApi\Modules\ConfirmationCode\Services\Creating' shared autowired service.
     *
     * @return \Apps\RestApi\Modules\ConfirmationCode\Services\Creating
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/Modules/ConfirmationCode/Services/Creating.php';
        include_once \dirname(__DIR__, 6).'/Core/ConfirmationCode/UseCases/Creating.php';
        include_once \dirname(__DIR__, 6).'/Core/ConfirmationCode/Ports/Changing.php';
        include_once \dirname(__DIR__, 6).'/MySQLAdapters/ConfirmationCode/Creating.php';
        include_once \dirname(__DIR__, 6).'/Core/ConfirmationCode/Ports/Getting.php';
        include_once \dirname(__DIR__, 6).'/MySQLAdapters/ConfirmationCode/Getting.php';

        return $container->privates['Apps\\RestApi\\Modules\\ConfirmationCode\\Services\\Creating'] = new \Apps\RestApi\Modules\ConfirmationCode\Services\Creating(new \Core\ConfirmationCode\UseCases\Creating(new \MySQLAdapters\ConfirmationCode\Creating(), ($container->privates['MySQLAdapters\\ConfirmationCode\\Getting'] ??= new \MySQLAdapters\ConfirmationCode\Getting()), new \AMQPAdapters\Notifying()));
    }
}
