<?php

namespace ContainerB5IdfhL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OJvfy0ZService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oJvfy0Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oJvfy0Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            '_authorization_service' => ['privates', 'Apps\\RestApi\\Modules\\User\\Services\\Authorization', 'getAuthorizationService', true],
        ], [
            '_authorization_service' => 'Apps\\RestApi\\Modules\\User\\Services\\Authorization',
        ]);
    }
}
