<?php

namespace ContainerB5IdfhL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoggerService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private 'AMQPAdapters\Logger' shared autowired service.
     *
     * @return \AMQPAdapters\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/AMQPAdapters/Logger.php';

        return $container->privates['AMQPAdapters\\Logger'] = new \AMQPAdapters\Logger($container->getEnv('string:RB_HOST'), $container->getEnv('string:RB_VHOST'), $container->getEnv('string:RB_USER'), $container->getEnv('string:RB_PASSWORD'), $container->getEnv('string:LOGGING_QUEUE'), $container->getEnv('string:ID_APPLICATION'));
    }
}
