<?php

namespace ContainerAaxBGMX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ur5WswCService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ur5WswC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ur5WswC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            '_creating_service' => ['privates', 'Apps\\RestApi\\Modules\\Sensor\\Services\\Creating', 'getCreating2Service', true],
        ], [
            '_creating_service' => 'Apps\\RestApi\\Modules\\Sensor\\Services\\Creating',
        ]);
    }
}
