<?php

namespace ContainerAaxBGMX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefreshingService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private 'Apps\RestApi\Modules\Session\Services\Refreshing' shared autowired service.
     *
     * @return \Apps\RestApi\Modules\Session\Services\Refreshing
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/Modules/Session/Services/Refreshing.php';
        include_once \dirname(__DIR__, 6).'/Core/Session/UseCases/Refreshing.php';

        return $container->privates['Apps\\RestApi\\Modules\\Session\\Services\\Refreshing'] = new \Apps\RestApi\Modules\Session\Services\Refreshing(new \Core\Session\UseCases\Refreshing($container->getEnv('string:ACCESS_TOKEN_SALT'), $container->getEnv('string:REFRESH_TOKEN_SALT')));
    }
}
