FROM php:latest-cli
FROM composer:latest

WORKDIR /tests
COPY . .
RUN docker-php-ext-install pdo mysqli pdo_mysql
RUN COMPOSER="composer.rest.json" COMPOSER_VENDOR_DIR="/vendor" composer install

CMD ["php", "/vendor/bin/phpunit", "tests"]



