<?php

namespace ContainerZISYkxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PYS7EpoService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pYS7Epo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pYS7Epo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            '_creating_service' => ['privates', 'Apps\\RestApi\\Modules\\Account\\Services\\Creating', 'getCreating3Service', true],
        ], [
            '_creating_service' => 'Apps\\RestApi\\Modules\\Account\\Services\\Creating',
        ]);
    }
}
