<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZISYkxh\Apps_RestApi_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZISYkxh/Apps_RestApi_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZISYkxh.legacy');

    return;
}

if (!\class_exists(Apps_RestApi_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZISYkxh\Apps_RestApi_KernelDevDebugContainer::class, Apps_RestApi_KernelDevDebugContainer::class, false);
}

return new \ContainerZISYkxh\Apps_RestApi_KernelDevDebugContainer([
    'container.build_hash' => 'ZISYkxh',
    'container.build_id' => 'c0d56151',
    'container.build_time' => 1678119432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZISYkxh');
