<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYTzH5GU\Apps_RestApi_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYTzH5GU/Apps_RestApi_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYTzH5GU.legacy');

    return;
}

if (!\class_exists(Apps_RestApi_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYTzH5GU\Apps_RestApi_KernelDevDebugContainer::class, Apps_RestApi_KernelDevDebugContainer::class, false);
}

return new \ContainerYTzH5GU\Apps_RestApi_KernelDevDebugContainer([
    'container.build_hash' => 'YTzH5GU',
    'container.build_id' => '3dc86dd7',
    'container.build_time' => 1677930408,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYTzH5GU');
