<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5IdfhL\Apps_RestApi_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5IdfhL/Apps_RestApi_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5IdfhL.legacy');

    return;
}

if (!\class_exists(Apps_RestApi_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5IdfhL\Apps_RestApi_KernelDevDebugContainer::class, Apps_RestApi_KernelDevDebugContainer::class, false);
}

return new \ContainerB5IdfhL\Apps_RestApi_KernelDevDebugContainer([
    'container.build_hash' => 'B5IdfhL',
    'container.build_id' => 'daf1a20f',
    'container.build_time' => 1678032346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5IdfhL');
