<?php

namespace ContainerYTzH5GU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorizationService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the private 'Apps\RestApi\Modules\User\Services\Authorization' shared autowired service.
     *
     * @return \Apps\RestApi\Modules\User\Services\Authorization
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/Modules/User/Services/Authorization.php';

        return $container->privates['Apps\\RestApi\\Modules\\User\\Services\\Authorization'] = new \Apps\RestApi\Modules\User\Services\Authorization(($container->privates['Core\\User\\UseCases\\Authorization'] ?? $container->load('getAuthorization2Service')));
    }
}
